In [91]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

cdata = pd.read_csv('carevaluation.csv')
cdata

vhigh vhigh.1      2   2.1  small   low  unacc
0     vhigh   vhigh      2     2  small   med  unacc
1     vhigh   vhigh      2     2  small  high  unacc
2     vhigh   vhigh      2     2    med   low  unacc
3     vhigh   vhigh      2     2    med   med  unacc
4     vhigh   vhigh      2     2    med  high  unacc
...     ...     ...    ...   ...    ...   ...    ...
1722    low     low  5more  more    med   med   good
1723    low     low  5more  more    med  high  vgood
1724    low     low  5more  more    big   low  unacc
1725    low     low  5more  more    big   med   good
1726    low     low  5more  more    big  high  vgood

[1727 rows x 7 columns]

#### 1)Use the given dataset and read the dataset with the names of the attribute to the dataset?

In [92]:
cdata.columns=['buying','maint','doors','persons','lug_boot','safety','classes']

In [93]:
cdata

buying  maint  doors persons lug_boot safety classes
0     vhigh  vhigh      2       2    small    med   unacc
1     vhigh  vhigh      2       2    small   high   unacc
2     vhigh  vhigh      2       2      med    low   unacc
3     vhigh  vhigh      2       2      med    med   unacc
4     vhigh  vhigh      2       2      med   high   unacc
...     ...    ...    ...     ...      ...    ...     ...
1722    low    low  5more    more      med    med    good
1723    low    low  5more    more      med   high   vgood
1724    low    low  5more    more      big    low   unacc
1725    low    low  5more    more      big    med    good
1726    low    low  5more    more      big   high   vgood

[1727 rows x 7 columns]

In [94]:
cdata['classes'].value_counts()

unacc    1209
acc       384
good       69
vgood      65
Name: classes, dtype: int64

#### 2)Check the information from the dataset and do the data processing by converting everthing into numeric form?

In [95]:
cdata.buying.replace(('vhigh','high','med','low'),(1,2,3,4), inplace=True)
cdata.maint.replace(('vhigh','high','med','low'),(1,2,3,4), inplace=True)
cdata.doors.replace(('2','3','4','5more'),(1,2,3,4), inplace=True)
cdata.persons.replace(('2','4','more'),(1,2,3), inplace=True)
cdata.lug_boot.replace(('small','med','big'),(1,2,3), inplace=True)
cdata.safety.replace(('low','med','high'),(1,2,3), inplace=True)
cdata.classes.replace(('unacc','acc','good','vgood'),(1,2,3,4), inplace=True)

In [96]:
cdata

buying  maint  doors  persons  lug_boot  safety  classes
0          1      1      1        1         1       2        1
1          1      1      1        1         1       3        1
2          1      1      1        1         2       1        1
3          1      1      1        1         2       2        1
4          1      1      1        1         2       3        1
...      ...    ...    ...      ...       ...     ...      ...
1722       4      4      4        3         2       2        3
1723       4      4      4        3         2       3        4
1724       4      4      4        3         3       1        1
1725       4      4      4        3         3       2        3
1726       4      4      4        3         3       3        4

[1727 rows x 7 columns]

#### 3)Split the dataset into training and testing portions?

In [68]:
data = cdata.values

In [69]:
data

array([[1, 1, 1, ..., 1, 2, 1],
       [1, 1, 1, ..., 1, 3, 1],
       [1, 1, 1, ..., 2, 1, 1],
       ...,
       [4, 4, 4, ..., 3, 1, 1],
       [4, 4, 4, ..., 3, 2, 3],
       [4, 4, 4, ..., 3, 3, 4]], dtype=int64)

In [50]:
X = data[:,0:6]

In [51]:
X

array([[1, 1, 1, 1, 1, 2],
       [1, 1, 1, 1, 1, 3],
       [1, 1, 1, 1, 2, 1],
       ...,
       [4, 4, 4, 3, 3, 1],
       [4, 4, 4, 3, 3, 2],
       [4, 4, 4, 3, 3, 3]], dtype=int64)

In [19]:
X.shape

(1727, 6)

In [70]:
Y = np.asarray(data[:,6], dtype="S6")
Y

array([b'1', b'1', b'1', ..., b'1', b'3', b'4'], dtype='|S6')

In [71]:
X_Train, X_Test, Y_Train, Y_Test = train_test_split(X, Y, test_size=0.2)

In [72]:
X_Train,X_Test,Y_Train, Y_Test

(array([[4, 2, 2, 2, 2, 3],
        [3, 1, 1, 2, 2, 2],
        [3, 2, 2, 3, 1, 1],
        ...,
        [1, 1, 4, 2, 3, 1],
        [2, 3, 2, 3, 1, 1],
        [4, 2, 1, 2, 2, 1]], dtype=int64), array([[3, 1, 2, 2, 1, 2],
        [1, 2, 2, 3, 2, 1],
        [1, 4, 4, 3, 2, 3],
        ...,
        [3, 1, 1, 1, 3, 1],
        [4, 4, 3, 3, 1, 1],
        [2, 1, 1, 2, 3, 3]], dtype=int64), array([b'2', b'1', b'1', ..., b'1', b'1', b'1'], dtype='|S6'), array([b'1', b'1', b'2', b'1', b'1', b'1', b'2', b'1', b'4', b'1', b'1',
        b'4', b'1', b'1', b'1', b'2', b'1', b'1', b'4', b'1', b'1', b'1',
        b'1', b'1', b'1', b'3', b'1', b'1', b'1', b'1', b'1', b'2', b'2',
        b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1',
        b'1', b'1', b'1', b'2', b'1', b'1', b'2', b'1', b'1', b'1', b'2',
        b'2', b'2', b'1', b'2', b'1', b'2', b'1', b'2', b'1', b'1', b'2',
        b'1', b'1', b'2', b'1', b'1', b'4', b'1', b'2', b'1', b'1', b'1',
        b'1', b'1', b'2', b'1

#### 4)Fit the KNN model?

In [97]:
knn = KNeighborsClassifier()

knn.fit(X_Train, Y_Train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [98]:
predict1 = knn.predict(X_Test)

score = accuracy_score(Y_Test, predict1)
print(score)

0.9393063583815029


#### 5)Choose the best k value within range of 25 and also calculate accuracy for each k value from 1 to 25? 

In [100]:
for k in range(1,26):
   knn = KNeighborsClassifier(n_neighbors=k)
   knn.fit(X_Train,Y_Train)
   print('Accuracy :', accuracy_score(Y_Test,predict1))

Accuracy : 0.9393063583815029
Accuracy : 0.9393063583815029
Accuracy : 0.9393063583815029
Accuracy : 0.9393063583815029
Accuracy : 0.9393063583815029
Accuracy : 0.9393063583815029
Accuracy : 0.9393063583815029
Accuracy : 0.9393063583815029
Accuracy : 0.9393063583815029
Accuracy : 0.9393063583815029
Accuracy : 0.9393063583815029
Accuracy : 0.9393063583815029
Accuracy : 0.9393063583815029
Accuracy : 0.9393063583815029
Accuracy : 0.9393063583815029
Accuracy : 0.9393063583815029
Accuracy : 0.9393063583815029
Accuracy : 0.9393063583815029
Accuracy : 0.9393063583815029
Accuracy : 0.9393063583815029
Accuracy : 0.9393063583815029
Accuracy : 0.9393063583815029
Accuracy : 0.9393063583815029
Accuracy : 0.9393063583815029
Accuracy : 0.9393063583815029
